In [1]:
import pandas as pd

In [2]:
mynewdata=pd.read_csv(r"C:\Users\ayushii\Downloads\DataSets-master\DataSets-master\Data_MVLR.csv")

In [3]:
mynewdata.head()

Petrol_tax  Average_income  Paved_Highways  Population_Driver_licence(%)  \
0         9.0            3571            1976                         0.525   
1         9.0            4092            1250                         0.572   
2         9.0            3865            1586                         0.580   
3         7.5            4870            2351                         0.529   
4         8.0            4399             431                         0.544   

   Petrol_Consumption  
0                 541  
1                 524  
2                 561  
3                 414  
4                 410

In [4]:
x_input=mynewdata.drop(["Petrol_Consumption"],axis=1)

In [5]:
x_input.head()

Petrol_tax  Average_income  Paved_Highways  Population_Driver_licence(%)
0         9.0            3571            1976                         0.525
1         9.0            4092            1250                         0.572
2         9.0            3865            1586                         0.580
3         7.5            4870            2351                         0.529
4         8.0            4399             431                         0.544

In [8]:
y_target=mynewdata["Petrol_Consumption"]

In [9]:
xin=x_input.values.reshape(len(x_input),4)

In [10]:
type(xin)

numpy.ndarray

In [11]:
yout=y_target.values.reshape(len(y_target),1)

In [12]:
x_train=xin[:-5]
x_test=xin[-5:]

In [13]:
y_train=yout[:-5]
y_test=yout[-5:]

In [14]:
from sklearn.linear_model import LinearRegression

In [15]:
myobj=LinearRegression()

In [16]:
mymodel=myobj.fit(x_train,y_train)

In [17]:
ya=y_test

In [18]:
yp=mymodel.predict(x_test)

In [19]:
from sklearn import metrics

In [20]:
import numpy as np

In [21]:
error=metrics.mean_squared_error(y_test,yp)

In [22]:
np.sqrt(error)

54.82046488767811

In [23]:
mymodel.coef_

array([[-2.72678083e+01, -6.91019875e-02, -3.99699825e-04,
         1.37211303e+03]])

In [24]:
mymodel.intercept_

array([298.31696451])

In [28]:
mymodel.predict([[7.8,1234,234,.65]])

array([[892.136149]])